### ISSUE TITLE
telegram官方的api也不行

### ISSUE THREAD

**Issue by AngelCloudflare** [souying/vercel-api-proxy#2]
这个可以设置正则或者其他方式吗？另外，如果使用自定义域名，如果暴露出去没有鉴权也是大问题

**Comment by souying** [comment]
> 这个可以设置正则或者其他方式吗？另外，如果使用自定义域名，如果暴露出去没有鉴权也是大问题


这个
fork 后可以改json 把https 或者http 改成你自己的 别人不会知道 服务端使用 没啥大问题

**Comment by node2014** [comment]
telegram 怎么设置，小白请问

**Comment by souying** [comment]
> telegram 怎么设置，小白请问

tg 只支持接口使用  不能直接做为客户端代理使用 举例 比如开发一些机器人应用 请求tg 官方接口 这些
